name: mattermost
title: Mattermost
icon: mattermost

services:
- name: mattermost
  title: Mattermost
  service: mattermost
  required: true
  main: true
  links:
  - name: postgres
    service: postgres
  - name: sendmail
    service: opensmtpd

- name: postgres
  title: PostgreSQL
  service: postgres
  required: true
  volumes:
  - name: data
    size: 20

- name: opensmtpd
  title: OpenSMTPD
  service: opensmtpd
